spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joinadmin
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    user:
      name: admin
      password: 1212

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.example.joinadmin: DEBUG